name: Build and Deploy
on: 
  workflow_dispatch
permissions:
  contents: read
  security-events: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Sign in to azurec
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |         
          az acr login -n sslablabacrskywalker
          docker tag myapp:latest sslablabacrskywalker.azurecr.io/myapp:latest
          docker push sslablabacrskywalker.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g ss-lab-rg \
          -n sslab-webappskywalker \
          --container-image-name sslablabacrskywalker.azurecr.io/myapp:latest \
          --container-registry-url https://sslablabacrskywalker.azurecr.io \
          --container-registry-user ${{secrets.ACR_USER}} \
          --container-registry-password ${{secrets.ACR_PWD}}